### ISSUE TITLE
Laravel 10.x support

### ISSUE THREAD

**Issue by 3ffusi0on** [Vonage/vonage-laravel#12]
The dependance to `illuminate/support` is not allowing the use of the package with Laravel 10.x

> Only one of these can be installed: illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4, v10.0.0, ..., v10.1.5], laravel/framework[v10.1.0, ..., v10.1.5]. laravel/framework replaces illuminate/support and thus cannot coexist with it.

**Comment by SecondeJK** [comment]
Shipped, thanks for flagging this!
