### ISSUE TITLE
Error on sending a WA message

### ISSUE THREAD

**Issue by alexmanase** [Vonage/vonage-laravel#18]
Hi there!

```php
use Vonage\Client;
use Vonage\Messages\Channel\WhatsApp\WhatsAppText;

$toNumber = '447123456789';
$message = 'Hello, this is a test message.';

$whatsAppMessage = new WhatsAppText(
	to: $toNumber,
	from: config('services.vonage.whatsapp.from_phone_number'),
	text: $message,
);

app(Client::class)
	->messages()
	->send($whatsAppMessage);
```

I used this code to send a message with WhatsApp, but I got the following error and I don't understand why.

<img width="1422" alt="image" src="https://github.com/Vonage/vonage-laravel/assets/10696975/20846ef7-5189-439e-a1f1-5bbf8aa54974">

When I run this command in CLI it works perfectly, and I've used the same phone numbers in my Laravel app.

<img width="921" alt="image" src="https://github.com/Vonage/vonage-laravel/assets/10696975/f4c42a02-4999-4881-9513-29e15ddf1c2d">

**Comment by dragonmantank** [comment]
Hello! The production version of the WhatsApp channel requires a WhatsApp business number being set up, where our sandbox environment will work with a personal number. Is the number that you are sending from in Laravel a proper WhatsApp Business number? If not, it will be rejected by our API.

**Comment by alexmanase** [comment]
> Is the number that you are sending from in Laravel a proper WhatsApp Business number?

No. I will check with a number that has WhatsApp Business.

Thanks!

**Comment by dragonmantank** [comment]
Also keep in mind the number must be registered with our API. If you do not currently have your WABA moved to us, you will need to contact sales/your account manager to work on that.

**Comment by alexmanase** [comment]
Alright. Thank you!
